# Generated by Django 4.2.5 on 2023-11-03 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alianza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0, unique=True)),
                ('fechadesafio', models.DateField()),
                ('desafios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TCI.desafio')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reglas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RondaEliminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRondaEliminacion', models.DateField()),
                ('desafios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TCI.desafio')),
                ('eliminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TCI.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('listaAlianza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TCI.alianza')),
                ('listaDetalleDesafio', models.ManyToManyField(related_name='temporada_detalle_desafio', to='TCI.detalle_desafio')),
                ('listaEquipo', models.ManyToManyField(to='TCI.equipo')),
                ('listaRondaEliminacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TCI.rondaeliminacion')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('apodo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('estadoParticipacion', models.BooleanField(default=True)),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TCI.habilidad')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TCI.pais')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='participantes',
            field=models.ManyToManyField(to='TCI.participante'),
        ),
        migrations.AddField(
            model_name='detalle_desafio',
            name='ganador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TCI.equipo'),
        ),
        migrations.AddField(
            model_name='desafio',
            name='equipos',
            field=models.ManyToManyField(to='TCI.equipo'),
        ),
        migrations.AddField(
            model_name='desafio',
            name='reglas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TCI.reglas'),
        ),
        migrations.AddField(
            model_name='alianza',
            name='Equipos',
            field=models.ManyToManyField(to='TCI.equipo'),
        ),
    ]
