# Generated by Django 4.2.7 on 2023-11-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desafio',
            name='reglas',
        ),
        migrations.AlterField(
            model_name='participante',
            name='estadoParticipacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='desafio',
            name='reglas',
            field=models.ManyToManyField(to='TCI.regla'),
        ),
    ]
