# Generated by Django 4.2.4 on 2023-11-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporada',
            name='puntos',
        ),
        migrations.AlterField(
            model_name='participante',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='participante',
            name='estadoParticipacion',
            field=models.BooleanField(default=True),
        ),
    ]
