# Generated by Django 4.2.7 on 2023-11-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCI', '0003_rename_desafios_rondaeliminacion_desafio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporada',
            name='listaRondaEliminacion',
        ),
        migrations.AddField(
            model_name='temporada',
            name='listaRondaEliminacion',
            field=models.ManyToManyField(to='TCI.rondaeliminacion'),
        ),
    ]
