# Generated by Django 4.2.5 on 2023-11-10 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCI', '0003_equipo_foto_participante_foto_temporada_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='foto',
            field=models.ImageField(default='static/img/defaultprofile', upload_to='static/img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='participante',
            name='foto',
            field=models.ImageField(default='static/img/defaultprofile', upload_to='static/img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='foto',
            field=models.ImageField(default='static/img/defailtprofile', upload_to='static/img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
