# Generated by Django 4.2.7 on 2023-11-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCI', '0004_remove_temporada_listarondaeliminacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporada',
            name='listaRondaEliminacion',
            field=models.ManyToManyField(blank=True, null=True, to='TCI.rondaeliminacion'),
        ),
    ]
