# Generated by Django 4.2.4 on 2023-11-24 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCI', '0006_remove_temporada_listaalianza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='foto',
            field=models.ImageField(default='static/img/defaultprofile.jpg', upload_to='src/TCI/static/img/defaultprofile.jpg', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
