# Generated by Django 4.2.4 on 2023-11-24 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCI', '0009_alter_equipo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='foto',
            field=models.ImageField(default='src/TCI/static/img/predeterminadoEquipo.png', upload_to='static/img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='foto',
            field=models.ImageField(default='src/TCI/static/img/predeterminadoTemporada.png', upload_to='static/img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
