# Generated by Django 4.2.5 on 2023-09-16 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TCI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reglas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='temporada',
            name='ganador',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='RondaEliminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRondaEliminacion', models.DateField()),
                ('eliminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TCI.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('apodo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('estadoParticipacion', models.CharField(max_length=50)),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TCI.habilidad')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TCI.pais')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='participantes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TCI.participante'),
        ),
        migrations.CreateModel(
            name='Detalle_desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('fechadesafio', models.DateField()),
                ('ganador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TCI.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('equipos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TCI.equipo')),
                ('reglas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TCI.reglas')),
            ],
        ),
        migrations.CreateModel(
            name='Alianza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
                ('listaEquipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TCI.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='temporada',
            name='listaAlianza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TCI.alianza'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='listaDesafio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TCI.desafio'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='listaEquipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TCI.equipo'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='listaRondaEliminacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TCI.rondaeliminacion'),
        ),
    ]
