# Generated by Django 4.2.5 on 2023-09-28 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TCI', '0002_equipo_habilidad_pais_reglas_temporada_ganador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporada',
            name='listaAlianza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TCI.alianza'),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='listaDesafio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TCI.desafio'),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='listaEquipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TCI.equipo'),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='listaRondaEliminacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TCI.rondaeliminacion'),
        ),
    ]
