# Generated by Django 4.2.5 on 2023-10-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCI', '0003_alter_temporada_listaalianza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='descripcion',
        ),
    ]
