# Generated by Django 4.2.4 on 2023-10-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCI', '0004_remove_pais_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='participantes',
        ),
        migrations.AddField(
            model_name='equipo',
            name='participantes',
            field=models.ManyToManyField(to='TCI.participante'),
        ),
    ]
