# Generated by Django 4.2.5 on 2023-10-23 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TCI', '0005_remove_equipo_participantes_equipo_participantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='puntos',
        ),
        migrations.RemoveField(
            model_name='temporada',
            name='ganador',
        ),
        migrations.RemoveField(
            model_name='temporada',
            name='listaDesafio',
        ),
        migrations.AddField(
            model_name='detalle_desafio',
            name='desafios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TCI.desafio'),
        ),
        migrations.AddField(
            model_name='rondaeliminacion',
            name='desafios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TCI.desafio'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='puntos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TCI.detalle_desafio', to_field='puntos'),
        ),
        migrations.AlterField(
            model_name='detalle_desafio',
            name='puntos',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.RemoveField(
            model_name='temporada',
            name='listaEquipo',
        ),
        migrations.AddField(
            model_name='temporada',
            name='listaEquipo',
            field=models.ManyToManyField(to='TCI.equipo'),
        ),
    ]
