classDiagram

    Temporada --> "1.." Detalle_desafio
    Detalle_desafio --> Desafio
    Temporada --> "1.." RondaEliminacion
    Temporada --> "1.." Equipo
    Equipo --> "1.." Participante
    Equipo --> "0.." Alianza
    Participante --> "1.." Pais
    Participante --> "1.." Habilidad
    Desafio --|> RondaEliminacion
    Desafio --> Reglas
    RondaEliminacion --> "1.." Equipo
    Desafio --> "1..*" Equipo

    class Equipo{
        String nombre
        Participante participantes
        int puntos
        conocerParticipantes()
        listarParticipantes()
        estadoAlianza()
    }
    class Participante{
        String nombre
        String descripcion
        String apellido
        Pais pais
        Habilidad habilidad
        String apodo
        String estadoParticipacion
        agregarParticipante()
        eliminarParticipante()
        cambiarEstado()
    }
    class Pais{
        String nombre
        String descripcion
    }
    class Habilidad{
        String nombre
        String descripcion
        setNombre()
        setDescripcion()
        getNombre()
        getDescripcion()
        crear()
    }
    class Temporada{
        int numero
        String nombre
        String ganador
        Equipo listaEquipo
        Desafio listaDesafio
        RondaEliminacion RondaEliminacion
        conocerEquipos()
        listarEquipos()
        conocerDesafios()
        conocerRondasEliminacion()
        listarDesafios()
        listarRondasELiminacion()
        enviarEquipos()
    }
    class Desafio{
        String nombre
        String descripcion
        Equipo equipos
        Reglas Reglas
    }
    class Detalle_desafio{
        int puntos
        Date FechaDesafio
    }
    class Reglas{
        String nombre
        String descripcion
    }
    class RondaEliminacion{
        Equipo eliminado
        eliminarEquipo()
    }
    class Alianza{
        String nombre
        String descripcion
        formarAlianza()
        verAlianzasFormadas()
        eliminarAlianzas()
    }